name: Test
on:
  - push:
    branches:
      - main
  - pullrequest

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: go test -v
